import type { Metadata } from "next";
import { Zeyada, Nothing_You_Could_Do, Allison, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const zeyada = Zeyada({
  variable: "--font-zeyada",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
})
const alison = Allison({
  variable: "--font-allison",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
})
const josefin = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
  display: "swap",
  weight: ["400","500","600","700"],
})
const nothingyoucouldo = Nothing_You_Could_Do({
  variable: "--font-nothingyoucouldo",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zeyada.variable} ${alison.variable} ${nothingyoucouldo.variable} ${josefin.variable} antialiased relative`}
      >
        {children}
        <div className="relative w-full flex justify-center z-40">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
